### ISSUE TITLE
Add Client Hints support

### ISSUE THREAD

**Issue by krpn** [51Degrees/device-detection-go#1]
Please add Client Hints support for Golang.

It's important because we can't detect Windows 11: https://docs.microsoft.com/en-us/microsoft-edge/web-platform/how-to-detect-win11

**Comment by jwrosewell** [comment]
We’re currently collecting feedback on Go features following the publication of an initial version with support for our V4 C code. The V4 C code supports UACH so it will be a case of exposing the additional functions to Go via CGO. The additional HTTP headers needed are added via [fiftyoneDegreesResultsHashFromEvidence](https://github.com/51Degrees/device-detection-cxx/blob/3cda350cebbbfc64069149ef3bf2cef5e1b93199/src/hash/hash.h#L568). You're welcome to add the necessary CGO code and tests and make a PR against this repo. Also if this is time critical for you then you could consider sponsoring the change. Please [contact us](https://51degrees.com/contact-us) if you'd like to follow this route.

**Comment by jwrosewell** [comment]
Further to the original issue concerning Microsoft's adoption of UACH. The [draft report](https://wicg.github.io/ua-client-hints/) (not  a draft specification or on track to become a specification) is still going through important changes with many issues outstanding. We have [highlighted](https://github.com/MicrosoftDocs/edge-developer/issues/1551) this to Microsoft.

**Comment by tungntpham** [comment]
Hi @krpn.

We have now released [v4.3.2](https://github.com/51Degrees/device-detection-go/releases/tag/v4.3.2) with support for UACH. Please have a look at the [example](https://github.com/51Degrees/device-detection-examples-go/tree/main/uach) to see how to enable the UACH support.

Kind regards,
Tung.
