### ISSUE TITLE
Add Device ID Support

### ISSUE THREAD

**Issue by krpn** [51Degrees/device-detection-go#2]
- [`DeviceId() (id string, err error)` method](https://github.com/51Degrees/device-detection-go/blob/main/dd/results_hash.go#L111)
- [`MatchDeviceId(id string) error` method](https://github.com/51Degrees/device-detection-go/blob/main/dd/results_hash.go#L443)

**Comment by tungntpham** [comment]
Hi @krpn,

We have now implemented this feature in release [v4.3.2](https://github.com/51Degrees/device-detection-go/releases/tag/v4.3.2). Please have a look at the [example](https://github.com/51Degrees/device-detection-examples-go/blob/main/dd/match_device_id_test.go) to see how they can be used.

Kind regards,
Tung.
