### ISSUE TITLE
Equivalent of `setAutoUpdate` and `setShareUsage` from the Java version

### ISSUE THREAD

**Issue by Krithika3** [51Degrees/device-detection-go#6]
We have tested device-detection-go in one of our golang projects and it has worked fine so far. We are currently looking for equivalents of the `setAutoUpdate` and `setShareUsage` methods that we  have used in the Java version. Appreciate your help. Thanks

**Comment by jorabin-51d** [comment]
There are no options to enable share usage or autoUpdate in the Go API.
