### ISSUE TITLE
User-Agent as fallback for Client Hints

### ISSUE THREAD

**Issue by krpn** [51Degrees/device-detection-go#7]
We've faced with problem.

If browser send `Sec-CH-UA-Platform` but not send `Sec-CH-UA-Platform-Version`, `51Degrees` won't detect `PlatformVersion`. Of course, we requested all `Client Hints` headers from browser. Browser decided to send `Sec-CH-UA-Platform` only.

For example:

```json
{
  "User-Agent":         "Mozilla/5.0 (Linux; Android 11; CPH1969) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36",
  "Sec-CH-UA":          "\".Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"103\", \"Chromium\";v=\"103\"",
  "Sec-CH-UA-Mobile":   "?1",
  "Sec-CH-UA-Platform": "\"Android\""
}
```

![image](https://user-images.githubusercontent.com/16793635/199545427-1f49d415-7e74-40d9-97cc-f569e37f68dc.png)

On the other hand, we have enough information to detect `Sec-CH-UA-Platform` in `User-Agent`:

![image](https://user-images.githubusercontent.com/16793635/199545895-f9f50c2f-9f8e-49bf-99e1-fd272a4d80d3.png)

`Enterprise-HashV41.hash`: latest
`device-detection-go`: v4.4.3 (latest)

**Comment by Steve51D** [comment]
Hi @krpn,

This is a choice we've made due to the increasing unreliability of information within the user-agent as Google deprecate parts of it.
You can read more on this in our [FAQ](http://51degrees.com/documentation/4.4/_info__f_a_qs.html#UserAgent_ContainsBetterData).

**Comment by krpn** [comment]
@Steve51D, sad, but thanks.

**Comment by krpn** [comment]
As a result, we decided to hide `Sec-CH-UA-Platform` header from `51Degrees` if we don't have `Sec-CH-UA-Platform-Version` header. Now it works better for us.

**Comment by krpn** [comment]
@Steve51D, of course, we understand this case. We prefer to get an approximate version rather than an unknown one.
